# Dockerfile.api and Dockerfile for Monitoring Service
FROM python:3.11-slim

WORKDIR /app
RUN apt-get update && apt-get install -y git
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY alembic.ini .
COPY migrations/ ./migrations/

COPY src ./src
# COPY models ./models
# COPY src/utils ./src/utils 


ENV PYTHONPATH=/app
ENV API_KEY_SECRET=SECRET_KEY

EXPOSE 8000

# CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]


