# Dockerfile.api
FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY alembic.ini .
COPY migrations/ ./migrations/


COPY src/api ./src/api
# COPY models ./models
# COPY src/utils ./src/utils 

ENV PYTHONPATH=/app
ENV API_KEY_SECRET = ${{secrets.API_KEY_SECRET}}
EXPOSE 8000

# CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]