# Dockerfile.airflow
FROM apache/airflow:2.10.2-python3.11

USER root
WORKDIR /opt/airflow

RUN apt-get update && apt-get install -y git

COPY dags ./dags
COPY src ./src

# Créer les répertoires de logs avec les bonnes permissions
RUN mkdir -p /opt/airflow/logs/scheduler && \
    chmod -R 777 /opt/airflow/logs

USER airflow
COPY requirements-airflow.txt .

RUN pip install --no-cache-dir -r requirements-airflow.txt