FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/mlflow_prometheus_exporter.py .

ENV EXPORTER_PORT=9100

CMD ["python", "mlflow_prometheus_exporter.py"]
