FROM apache/airflow:2.10.2-python3.11

USER root
WORKDIR /opt/airflow

RUN apt-get update && apt-get install -y git

COPY dags ./dags
COPY src ./src

RUN mkdir -p /opt/airflow/logs/scheduler && \
    chown -R airflow:airflow /opt/airflow/logs && \
    chmod -R 755 /opt/airflow/logs

USER airflow
COPY requirements-airflow.txt .

RUN pip install --no-cache-dir -r requirements-airflow.txt