groups:
  - name: api_performance
    rules:
      - alert: HighPredictionLatencyP95
        expr: |
          histogram_quantile(
            0.95,
            sum(rate(prediction_latency_seconds_bucket[5m])) by (le)
          ) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High p95 latency on predictions (>500ms)
          description: Prediction latency p95 is above threshold for 5 minutes.

      - alert: HighPredictionErrorRate
        expr: |
          sum(rate(prediction_errors_total[5m]))
            /
          sum(rate(prediction_requests_total[5m])) > 0.05
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: High prediction error rate (>5%)
          description: Error rate has exceeded 5% over the last 10 minutes.

      - alert: DataDriftDetected
        expr: max_over_time(feature_drift_statistic[30m]) > 0.2
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: Potential data drift (KS D > 0.2)
          description: Feature drift statistic exceeded threshold in last 30 minutes.

      - alert: LowModelAccuracy
        expr: model_accuracy < 0.8
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Model accuracy degraded (<0.8)
          description: Online accuracy (from labeled requests) is below 0.8.
