# name: Deploy to Azure VM


name: CD to Azure VM 

on:
  push:
    branches:
      - refactor/mlops-improvements  # Déclenche le CD sur ta branche

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du repo GitHub Actions
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Déploiement minimal sur Azure VM via SSH (key-based)
      - name: Deploy repo to Azure VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            # --- Créer le répertoire et cloner la branche si nécessaire ---
            cd /home/${{ secrets.AZURE_USER }}/Customer_Churn || git clone -b refactor/mlops-improvements https://github.com/mamad9633/Customer_Churn.git Customer_Churn

            # --- Aller dans le répertoire du projet ---
            cd /home/${{ secrets.AZURE_USER }}/Customer_Churn

            # --- Mettre à jour la branche ---
            git reset --hard
            git pull origin refactor/mlops-improvements

            # --- Information de succès ---
            echo " Repo mis à jour sur la branche refactor/mlops-improvements"
